import Head from 'next/head'
import Image from 'next/image'

// IMPORT COMPOSANT BANNER
import Banner from '@/components/Banner/Banner'
import '../components/Banner/banner.module.css'


import styles from '@/styles/Home.module.css'
import Navbar from '@/components/navbar/Navbar'
import Card from '@/components/Card/Card'



export default function Home() {
  return (
    <>
      <Head>
        <title>Netflix</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar userName="anil.celik075@gmail.com" />
      <Banner title='Clifford' subTitle='a very cute dog' imgUrl='/static/Clifford.webp'/>
     <Card /> 
    </>
  )
}
