import Head from "next/head";

// IMPORT COMPOSANT BANNER
import Banner from "@/components/Banner/Banner";
import "../components/Banner/banner.module.css";

import styles from "@/styles/Home.module.css";
import Navbar from "@/components/navbar/Navbar";

import SectionCard from "@/components/Card/SectionCard";

import { getPopularVideos, getVideos, getWatchItAgainVideos } from "../lib/videos";

import RedirectUser from "@/utils/redirectUser";


export async function getServerSideProps(context) {
  const marvelVideos = await getVideos("marvel trailer");
  const productivityVideos = await getVideos("productivity");
  const travelVideos = await getVideos("travel");
  const popularVideos = await getPopularVideos();

  const {user_id, token} = await RedirectUser(context)

  if (!user_id) {
    return {
      props: {},
      redirect: {
        destination: "/login",
        permanent: false,
      },
    };
  }
 
  const watchItAgainVideos =  await getWatchItAgainVideos(user_id, token)


  return {
    props: { marvelVideos, productivityVideos, travelVideos, popularVideos, watchItAgainVideos},
  };
}

export default function Home({
  marvelVideos,
  productivityVideos,
  travelVideos,
  popularVideos,
  watchItAgainVideos
}) {
  return (
    <>
      <Head>
        <title>Netflix</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={styles.main}>
        <Navbar userName="anil.celik075@gmail.com" />
        <Banner
          videoId="sGbxmsDFVnE"
          title="Clifford"
          subTitle="a very cute dog"
          imgUrl="/static/Clifford.webp"
        />

        <div className={styles.sectionWrapper}>
          <SectionCard title="Marvel" size="large" videos={marvelVideos} />
          <SectionCard title="Watch it again" size="small" videos={watchItAgainVideos} />

          <SectionCard title="Travel" size="small" videos={travelVideos} />
          <SectionCard
            title="Productivity"
            size="medium"
            videos={productivityVideos}
          />
          <SectionCard title="Popular" size="small" videos={popularVideos} />
        </div>
      </div>
      {/* <SectionCard title="Disney" size="medium" />
      <SectionCard title="Disney" size="small" /> */}
    </>
  );
}
